version: '3.8'
services:
  api:
    build: ../../services/api
    env_file: ../../.env.template
    ports:
      - '3000:3000'
    networks:
      - bot2-net

  worker:
    build: ../../services/worker
    env_file: ../../.env.template
    networks:
      - bot2-net

  scraper:
    build: ../../services/scraper
    depends_on:
      - redis
    env_file: ../../.env.template
    networks:
      - bot2-net

  redis:
    image: redis:7
    ports:
      - '6379:6379'
    networks:
      - bot2-net

networks:
  bot2-net:
    driver: bridge
